# Databases: Examples

This notebook provides practical code examples for working with relational and NoSQL databases in Python. Each example demonstrates key concepts and best practices for database interaction, querying, and management.

---

## Table of Contents
1. [Connecting to a Relational Database (SQLite)](#connecting-to-a-relational-database-sqlite)
2. [Basic SQL Operations](#basic-sql-operations)
3. [Using SQLAlchemy ORM](#using-sqlalchemy-orm)
4. [Working with NoSQL (MongoDB)](#working-with-nosql-mongodb)
5. [Transactions and Error Handling](#transactions-and-error-handling)
6. [Indexing and Query Optimization](#indexing-and-query-optimization)

---

In [ ]:
# 1. Connecting to a Relational Database (SQLite)
import sqlite3

# Create an in-memory SQLite database and connect
db = sqlite3.connect(':memory:')
cursor = db.cursor()

# 2. Basic SQL Operations
# Create a table
cursor.execute('''CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, age INTEGER)''')
# Insert data
cursor.execute('''INSERT INTO users (name, age) VALUES (?, ?)''', ('Alice', 30))
cursor.execute('''INSERT INTO users (name, age) VALUES (?, ?)''', ('Bob', 25))
db.commit()
# Query data
cursor.execute('SELECT * FROM users')
print(cursor.fetchall())

# 3. Using SQLAlchemy ORM
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base, sessionmaker

engine = create_engine('sqlite:///:memory:')
Base = declarative_base()

class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    age = Column(Integer)

Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

# Add a user
user = User(name='Charlie', age=28)
session.add(user)
session.commit()
# Query users
for user in session.query(User):
    print(user.name, user.age)

# 4. Working with NoSQL (MongoDB)
# Note: Requires running MongoDB instance and pymongo installed
# from pymongo import MongoClient
# client = MongoClient('mongodb://localhost:27017/')
# db = client['testdb']
# collection = db['users']
# collection.insert_one({'name': 'Dana', 'age': 22})
# print(list(collection.find()))

# 5. Transactions and Error Handling
try:
    cursor.execute('BEGIN TRANSACTION;')
    cursor.execute('INSERT INTO users (name, age) VALUES (?, ?)', ('Eve', 35))
    db.commit()
except Exception as e:
    db.rollback()
    print('Transaction failed:', e)

# 6. Indexing and Query Optimization
# Create an index on the age column
cursor.execute('CREATE INDEX idx_age ON users(age)')
# Query using the index
cursor.execute('SELECT * FROM users WHERE age > 25')
print(cursor.fetchall())