# Databases: Solutions

This notebook provides detailed solutions to the Databases exercises. Review the solutions after attempting the exercises to reinforce your understanding and learn best practices.

---

## Table of Contents
1. [SQLite: Basic Operations](#sqlite-basic-operations)
2. [SQL Queries](#sql-queries)
3. [SQLAlchemy ORM](#sqlalchemy-orm)
4. [NoSQL with MongoDB](#nosql-with-mongodb)
5. [Transactions and Error Handling](#transactions-and-error-handling)
6. [Indexing and Optimization](#indexing-and-optimization)

---

In [ ]:
# 1. SQLite: Basic Operations
import sqlite3
db = sqlite3.connect(':memory:')
cursor = db.cursor()
cursor.execute('''CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL)''')
cursor.execute('''INSERT INTO products (name, price) VALUES (?, ?)''', ('Pen', 5.0))
cursor.execute('''INSERT INTO products (name, price) VALUES (?, ?)''', ('Notebook', 25.0))
cursor.execute('''INSERT INTO products (name, price) VALUES (?, ?)''', ('Bag', 50.0))
db.commit()
cursor.execute('SELECT * FROM products')
print(cursor.fetchall())

# 2. SQL Queries
cursor.execute('SELECT * FROM products')
print(cursor.fetchall())
cursor.execute('SELECT * FROM products WHERE price > 20')
print(cursor.fetchall())
cursor.execute('UPDATE products SET price = 30 WHERE name = "Pen"')
db.commit()
cursor.execute('DELETE FROM products WHERE name = "Bag"')
db.commit()

# 3. SQLAlchemy ORM
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base, sessionmaker
engine = create_engine('sqlite:///:memory:')
Base = declarative_base()
class Customer(Base):
    __tablename__ = 'customers'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    email = Column(String)
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()
session.add(Customer(name='Alice', email='alice@email.com'))
session.add(Customer(name='Bob', email='bob@email.com'))
session.commit()
for customer in session.query(Customer):
    print(customer.name, customer.email)

# 4. NoSQL with MongoDB
# from pymongo import MongoClient
# client = MongoClient('mongodb://localhost:27017/')
# db = client['testdb']
# books = db['books']
# books.insert_one({'title': '1984', 'author': 'George Orwell'})
# print(list(books.find()))

# 5. Transactions and Error Handling
try:
    cursor.execute('BEGIN TRANSACTION;')
    cursor.execute('INSERT INTO products (name, price) VALUES (?, ?)', ('Pencil', 2.0))
    cursor.execute('INSERT INTO products (name, price) VALUES (?, ?)', ('Eraser', 1.0))
    db.commit()
except Exception as e:
    db.rollback()
    print('Transaction failed:', e)

# 6. Indexing and Optimization
cursor.execute('CREATE INDEX idx_price ON products(price)')
cursor.execute('SELECT * FROM products WHERE price > 10')
print(cursor.fetchall())